pipeline{

    agent any
     parameters{
      string(name: 'SPEC', defaultValue:"cypress/integration/**/** ", description: "Enter the scrip path that you want to execute:  " )
    choice(name: "BROWSER", choices:['chrome','edge','firefox'], description: "Where you want to execute to execute: ")

     }
     options{
           ansiColor('xterm')
           }
    stages{
        stage('deploying')
        {
            echo 'Building the application'
        }
        stage("Testing")
        {
            steps{
                sh 'npn i'
                sh "npx cypress run --browser ${BROWSER} --spec ${SPEC}"
            }
        }
        stage("Deploying")
        {
            echo " Deploy the application"
        }
    }
}
post
{
 always
 {
 publishHTML([allowMissing:false, alwaysLinkToLastBuild:false,keepAll:true])
 }
}